### ISSUE TITLE
Opening aOS help causes error

### ISSUE THREAD

**Issue by Meowcat285** [MineAndCraft12/AaronOS#2]
Opening aOS help causes error.
The error is below
![Screen Shot 2019-03-19 at 5 03 25 PM](https://user-images.githubusercontent.com/13440415/54649815-f8a30c00-4a68-11e9-9aa0-2192170a6868.png)

**Comment by CerebralDatabank** [comment]
@mix12 can i fix this? :)
would be my first time being assigned to a GitHub issue

**Comment by MineAndCraft12** [comment]
Fixed it, was just a small typo. But I will keep you in mind Cerebral :P
