### ISSUE TITLE
Files with filenames containing the "." character cause problems

### ISSUE THREAD

**Issue by CerebralDatabank** [MineAndCraft12/AaronOS#4]
The File Manager prohibits users from creating filenames containing `..`, but not `.`.
Consequently, it is possible to create irrationally named files such as `..string`.

The Text Editor seems to be able to handle such filenames, but attempting to invoke the context menu on any file with a `.` character seems to fail (errors such as "SyntaxError: Missing ']'" and `SyntaxError: Invalid escape sequence`).

![aos-dot-filename](https://user-images.githubusercontent.com/24465111/55507961-7bf25f00-561e-11e9-9940-51d1e8f09e0e.png)

**Comment by MineAndCraft12** [comment]
Yeah, I need to change the faux-file-extension thing. I'll probably change ".string" to "(string)" or something like that. As for context menu, you're right; I need to fix that.

**Comment by MineAndCraft12** [comment]
I've made a modification to how the filetype description is located to prevent the first bit of this issue from happening. (the ".string" wasn't actually part of the name, explains why it caused confusions and "names" that shouldn't exist)

Second part of issue will be addressed soon.

**Comment by MineAndCraft12** [comment]
Fixed
